; Apio project file
; https://fpgawars.github.io/apio/docs/project-file

; SPDX-DocumentNamespace: https://github.com/ProfMarkLabs/i2s-tdm
; SPDX-FileCopyrightText: (C) 2026 Mark Warriner
; SPDX-License-Identifier: 0BSD

[common]
board = icefun
top-module = main
default-testbench = main_tb.sv

; TDM aggregator with 8 mics
[env:tdm8]
constraint-file = main_tdm8.pcf
defines = TDM8

; TDM aggregator with 24 mics
[env:tdm24]
constraint-file = main_tdm24.pcf
defines = TDM24
